-- Spending & Income Alerts (see claude.md "Spending & Income Alerts" section).
-- Deterministic, rule-based detection — no LLM in this path. This migration
-- creates the alerts table, RLS, the set-based rule-evaluation function, and
-- the pg_cron schedule that invokes the generate-alerts Edge Function daily.

-- 1. Table
create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  -- income_drop is reserved for a possible future rule (claude.md's Data
  -- Model section lists it as an example type, but no current trigger
  -- condition produces it — only category_spike, overspend, and
  -- wishlist_off_pace are actually generated by evaluate_alerts() below).
  type text not null check (type in ('category_spike', 'overspend', 'wishlist_off_pace', 'income_drop')),
  category_id uuid references public.categories(id) on delete set null,
  period text not null, -- e.g. '2026-07'
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  pushed_at timestamptz -- left null; populated by a future FCM push fast-follow
);

-- Defense-in-depth dedup for category_spike/overspend (category_id-bearing
-- and single-per-user-per-period rows). wishlist_off_pace additionally dedups
-- on metadata->>'goal_id' inside evaluate_alerts(), since Postgres unique
-- indexes treat NULL category_id values as distinct from one another and so
-- can't by themselves prevent duplicate per-goal alerts.
create unique index if not exists alerts_dedup_idx
  on public.alerts (user_id, type, category_id, period);

create index if not exists alerts_user_created_idx
  on public.alerts (user_id, created_at desc);

alter table public.alerts enable row level security;

create policy "alerts_select_own" on public.alerts
  for select using (auth.uid() = user_id);

-- INSERT is actually performed by the service-role generate-alerts Edge
-- Function, which bypasses RLS entirely. This policy is defense-in-depth /
-- future-proofing for any client-side write path, matching the mandatory
-- auth.uid() = user_id pattern required on every table.
create policy "alerts_insert_own" on public.alerts
  for insert with check (auth.uid() = user_id);

create policy "alerts_update_own" on public.alerts
  for update using (auth.uid() = user_id);

create policy "alerts_delete_own" on public.alerts
  for delete using (auth.uid() = user_id);

-- 2. Rule evaluation, set-based across all users in one pass (cheaper than
-- per-user aggregation in Edge Function JS — fewer round trips, lower
-- egress, consistent with claude.md's Performance Rules).
create or replace function public.evaluate_alerts()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_period text := to_char(date_trunc('month', now()), 'YYYY-MM');
  v_month_start timestamptz := date_trunc('month', now());
  v_prev_month_start timestamptz := date_trunc('month', now()) - interval '1 month';
  v_threshold numeric := 1.25;   -- category spend > 125% of previous period
  v_pace_ratio numeric := 0.75;  -- wishlist behind 75% of linear-pace expectation
  v_inserted integer := 0;
  v_count integer;
begin

  -- Rule A: category_spike — this month's category expense > 1.25x last month's
  with cur_month as (
    select user_id, category_id, sum(amount) as total
    from transactions
    where type = 'expense' and is_deleted = false and date >= v_month_start
    group by user_id, category_id
  ),
  prev_month as (
    select user_id, category_id, sum(amount) as total
    from transactions
    where type = 'expense' and is_deleted = false
      and date >= v_prev_month_start and date < v_month_start
    group by user_id, category_id
  )
  insert into alerts (user_id, type, category_id, period, message, metadata)
  select
    cur.user_id,
    'category_spike',
    cur.category_id,
    v_period,
    format(
      '%s spending is up %s%% this month — %s vs %s last month.',
      c.name,
      round(((cur.total - prev.total) / prev.total) * 100),
      cur.total,
      prev.total
    ),
    jsonb_build_object(
      'current_amount', cur.total,
      'previous_amount', prev.total,
      'percent_change', round(((cur.total - prev.total) / prev.total) * 100, 1)
    )
  from cur_month cur
  join prev_month prev on prev.user_id = cur.user_id and prev.category_id = cur.category_id
  join categories c on c.id = cur.category_id
  where prev.total > 0
    and cur.total > prev.total * v_threshold
    and not exists (
      select 1 from alerts a
      where a.user_id = cur.user_id and a.type = 'category_spike'
        and a.category_id = cur.category_id and a.period = v_period
    )
  on conflict (user_id, type, category_id, period) do nothing;
  get diagnostics v_count = row_count;
  v_inserted := v_inserted + v_count;

  -- Rule B: overspend — this month's total expense > total income
  with monthly_totals as (
    select
      user_id,
      coalesce(sum(amount) filter (where type = 'income'), 0) as income,
      coalesce(sum(amount) filter (where type = 'expense'), 0) as expense
    from transactions
    where is_deleted = false and date >= v_month_start
    group by user_id
  )
  insert into alerts (user_id, type, category_id, period, message, metadata)
  select
    t.user_id,
    'overspend',
    null,
    v_period,
    format(
      'You''ve spent %s more than you''ve earned this month (%s income vs %s expenses).',
      t.expense - t.income, t.income, t.expense
    ),
    jsonb_build_object(
      'current_amount', t.expense,
      'previous_amount', t.income,
      'percent_change', case when t.income > 0
        then round(((t.expense - t.income) / t.income) * 100, 1) else null end
    )
  from monthly_totals t
  where t.expense > t.income
    and not exists (
      select 1 from alerts a
      where a.user_id = t.user_id and a.type = 'overspend'
        and a.category_id is null and a.period = v_period
    )
  on conflict (user_id, type, category_id, period) do nothing;
  get diagnostics v_count = row_count;
  v_inserted := v_inserted + v_count;

  -- Rule C: wishlist_off_pace — actual savings behind linear-pace expectation
  -- for the goal's deadline. Only evaluated for active, non-expired goals
  -- that have a deadline (pacing is undefined without one).
  with paced as (
    select
      w.*,
      least(
        greatest(
          extract(epoch from (now() - w.created_at))
            / nullif(extract(epoch from (w.deadline - w.created_at)), 0),
          0
        ),
        1
      ) as expected_fraction
    from wishlist w
    where w.is_deleted = false
      and w.deadline is not null
      and w.deadline > now()
      and w.current_amount < w.target_amount
  )
  insert into alerts (user_id, type, category_id, period, message, metadata)
  select
    p.user_id,
    'wishlist_off_pace',
    null,
    v_period,
    format(
      '"%s" is behind pace — you''re at %s%% but should be around %s%% by now.',
      p.name,
      round((p.current_amount / p.target_amount) * 100),
      round(p.expected_fraction * 100)
    ),
    jsonb_build_object(
      'goal_id', p.id,
      'current_amount', p.current_amount,
      'previous_amount', round(p.target_amount * p.expected_fraction, 2),
      'percent_change', round(
        ((p.current_amount - (p.target_amount * p.expected_fraction))
          / nullif(p.target_amount * p.expected_fraction, 0)) * 100, 1)
    )
  from paced p
  where p.expected_fraction > 0
    and p.current_amount < (p.target_amount * p.expected_fraction * v_pace_ratio)
    and not exists (
      select 1 from alerts a
      where a.user_id = p.user_id and a.type = 'wishlist_off_pace'
        and a.period = v_period and a.metadata->>'goal_id' = p.id::text
    );
  get diagnostics v_count = row_count;
  v_inserted := v_inserted + v_count;

  return v_inserted;
end;
$$;

revoke all on function public.evaluate_alerts() from public, anon, authenticated;
grant execute on function public.evaluate_alerts() to service_role;

-- 3. Scheduled invocation. pg_cron has no user JWT, so the Edge Function runs
-- with verify_jwt = false and instead checks a dedicated shared secret (not
-- the service-role key itself, to keep blast radius small if it leaks),
-- stored in Supabase Vault so this committed migration never embeds the
-- actual secret value.
--
-- One-time manual deployment steps (NOT run by this migration):
--   supabase secrets set CRON_SECRET=<random-value>
--   select vault.create_secret('<same-random-value>', 'cron_secret');
create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

select cron.schedule(
  'generate-alerts-daily',
  '0 2 * * *', -- 02:00 UTC daily
  $$
  select net.http_post(
    url := 'https://drzokxtinnicbldxegnu.supabase.co/functions/v1/generate-alerts',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', (
        select decrypted_secret from vault.decrypted_secrets
        where name = 'cron_secret'
      )
    ),
    body := '{}'::jsonb
  );
  $$
);
